runtime: php
env: flex

beta_settings:
  cloud_sql_instances: dark-carport-344412:europe-southwest1:random-database=tcp:3306

runtime_config:
  document_root: .

automatic_scaling:
  min_num_instances: 5
  max_num_instances: 15
  cpu_utilization:
    target_utilization: 0.5
  max_concurrent_requests: 30
  target_throughput_utilization: 0.5